version: "3.8"

services:
  sentinel1:
    image: redis:7.2
    container_name: sentinel1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - redis-net
  sentinel2:
    image: redis:7.2
    container_name: sentinel2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - redis-net
  sentinel3:
    image: redis:7.2
    container_name: sentinel3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - redis-net


networks:
  redis-net:
    driver: bridge
    name: redis-net
